config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get '/index', to: 'welcome#index'
	
  resources :users, only: [:new, :create]
  get '/registrate', to: 'users#new'
  get '/ranking', to: 'users#show'

  resources :guides do
    resources :comments
  end

  get '/guides', to: 'guides#index'
  #post '/users/:id/guides/new', to: 'guides#new'

  resources :profiles

  resource :session, only: [:new, :create, :destroy]
  get 'login' => "sessions#new", as: "login"
  get 'logout' => "sessions#destroy", as: "logout"
  #resources :profiles do
  #  member do
  #    get :edit
  #  end
  #end
end

app/models/profile.rb
class Profile < ApplicationRecord
  mount_uploader :photo, ImageUploader
  belongs_to :user, optional: true

  scope :minirank, -> {select('users.id, users.name, profiles.points, profiles.photo, profiles.bio').joins(:user).order('points DESC').limit(3)}
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def new
    @profile = Profile.new
  end

  def show
    @user = User.find_by_id(params[:id])
    @profile = @user.profile
  end

  def edit
   @profile = Profile.find_by_id(params[:id])
   redirect_to root_path, alert: "Operación no permitida." unless @profile
  end
 
  def update
    @profile = Profile.find_by_id(params[:id])
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Perfil actualizado.' }
      else
        format.html { render :edit }
      end
    end
  end 

  def profile_params
      params.require(:profile).permit(:points, :bio, :categorie, :photo, :user_id)
  end
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true, html: {multipart: true}) do |form| %>
  
  <div class="field">
    <%= form.label :"Foto Principal" %>
    <%= form.file_field :photo, id: :profile_photo %>
  </div><br>

  <div class="field">
    <%= form.label :Biografía %>
    <%= form.text_area :bio, id: :profile_bio %>
  </div>

  <div class="actions">
    <%= form.submit :"Guardar Cambios" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<% if @profile.id == current_user.id %>
  <h3>Editar Perfil</h3>

  <%= render 'form', profile: @profile %>

<% else %>
  <%= controller.redirect_to root_path %>
<% end %>

app/views/profiles/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Perfil de Usuario</title>
</head>
<body>
<body>
<div id="fondoPerfil">
    <div id="imagenUsuario">
        <% if @profile.photo.blank? %>
          <%= image_tag('usuario.jpg', alt: "Foto de Perfil1") %>
        <% else %>
          <%= image_tag(@profile.photo, alt: "Foto de Perfil") %>
        <% end %>
    </div>
</div>

<div id="contenido">
    <div id="principal">
        <div class="menu menuAportes">
            <ul>
                
                <li><a class="noReload" href="myPosts.html">Mis Aportes</a></li>
                <li><a class="noReload" href="myValuations.html">Mis Valoraciones</a></li>
                <li><a class="noReload" href="trending.html">Trending</a></li>
            </ul>
        </div>
        <div id="page" class="fondoTablon"></div>
    </div>

    <div id="lateral">
        <div id="rolUsuario">
            <div class="inline">
               <h4><%= @user.name %></h4>
            </div>
            <div class="inline">
                <h6 id="rango">(<%= @profile.categorie %>)</h6>&nbsp
            </div>-
            <div class="inline">
                <h6 id="puntos"><%= @profile.points %></h6>&nbsp<h6>Puntos</h6>
            </div>
        </div>
	<div >
	  <p> Biografia: <%= @profile.bio %></p>
	  <% if logged_in? %>
            <% if @user.id == current_user.id %>
              <span class="actions">
                <h5><%= link_to "editar", edit_profile_path(current_user) %></h5>
              </span>
            <% end %>
	  <% end %>
	</div>
        <div class="fondoLateral">
            <h6 class="tituloTablon">Stats</h6>
            <div class="inline">
                <ul class="nostyle">
                    <li><strong>Colaboraciones:</strong> X</li>
                    <li><strong>Comentarios:</strong> X</li>
                    <li><strong>Valoraciones:</strong> X</li>
                </ul>
                <ul class="nostyle">
                    <li><strong>Valoraciones recibidas:</strong> X</li>
                    <li><strong>Hilos creados:</strong> X</li>
                </ul>
            </div>
        </div>
        <div class="fondoLateral">
            <h6 class="tituloTablon">Mis Estadísticas</h6>
            <ul class="nostyle">
                <li><strong>01/12/2017</strong> +X Puntos</li>
                <li><strong>13/11/2017</strong> +X Puntos</li>
                <li><strong>30/10/2017</strong> -X Puntos</li>
                <li><strong>19/10/2017</strong> +X Puntos</li>
                <li><strong>21/09/2017</strong> -X Puntos</li>
            </ul>
        </div>
    </div>
</div>