config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get '/index', to: 'welcome#index'
	
  resources :users, only: [:new, :create]
  get '/registrate', to: 'users#new'
  get '/ranking', to: 'users#show'

  resources :guides do
    resources :comments
  end

  get '/guides', to: 'guides#index'
  #post '/users/:id/guides/new', to: 'guides#new'

  resources :profiles

  resource :session, only: [:new, :create, :destroy]
  get 'login' => "sessions#new", as: "login"
  get 'logout' => "sessions#destroy", as: "logout"
  #resources :profiles do
  #  member do
  #    get :edit
  #  end
  #end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :guide
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_guide, except: :destroy
  before_action :authenticate, only: :destroy
  
  def create
    @comment = @guide.comments.new(comment_params)
    if @comment.save
      redirect_to @guide, notice: 'gracias por su comentario'
    else
      redirect_to @guide, alert: 'no ha sido posible añadir el comentario'
    end
  end
  
  def destroy
    @guide = current_user.guides.find_by_id(params[:guide_id])
    if @guide.nil?
       redirect_to :index, notice: "operación no permitida"
     end
    @comment = @guide.comments.find_by_id(params[:id])
    @comment.destroy
    redirect_to @guide, notice: "comentario eliminado"
  end

  private
    def load_guide
      @guide = Guide.find_by_id(params[:guide_id])
    end
    
    def comment_params
      params.require(:comment).permit(:name, :body)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %> 
  <h3>
    <%= comment.name %> said:
    <% if @guide.owned_by? current_user %> 
      <span class="actions">
         <%= link_to "Eliminar Comentario", guide_comment_path(guide_id: @guide, id: comment), method: :delete, data: {confirm: "¿Seguro?"} %> 
      </span>
     <% end %> 
  </h3>
   <%= comment.body %> 
<% end %> 

app/views/comments/new.html.erb
<%= form_with(model: [@guide, @guide.comments.new], local: true) do |form| %>
  <div class="field">
    <%= form.label :Nombre %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :Comentario %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit 'Enviar' %>
  </div>
<% end %>

app/views/comments/show.html.erb
<table id="espaciado" class="table table-striped">
            <tbody>
	    <% @comments.each do |comment| %>
                <tr>
           	    <td><%= comment.body %></td>
		    <td><%= comment.published_at %></td>
                </tr>
	    <% end %>
            </tbody>
        </table>