config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get '/index', to: 'welcome#index'
	
  resources :users, only: [:new, :create]
  get '/registrate', to: 'users#new'
  get '/ranking', to: 'users#show'

  resources :guides do
    resources :comments
  end

  get '/guides', to: 'guides#index'
  #post '/users/:id/guides/new', to: 'guides#new'

  resources :profiles

  resource :session, only: [:new, :create, :destroy]
  get 'login' => "sessions#new", as: "login"
  get 'logout' => "sessions#destroy", as: "logout"
  #resources :profiles do
  #  member do
  #    get :edit
  #  end
  #end
end

app/models/guide.rb
class Guide < ApplicationRecord
  mount_uploader :photo, ImageUploader

  belongs_to :user, optional: true
  has_many :comments

  scope :guide_list, -> {select('guides.id, guides.user_id, guides.photo, guides.title, guides.trophies, guides.category, guides.updated_at, users.name').joins(:user).order('guides.updated_at DESC').limit(10)}
  validates :body, :title, :trophies, :category, presence: {message: "el campo no puede quedar vacío"}
  validates :photo, presence: {message: "Debe añadir una foto"}

  def owned_by?(owner)
    return false unless owner.is_a? User
    user == owner
  end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  before_action :set_guide, only: [:show]

  def new 
    @guide = Guide.new
  end

  def create
    @guide = current_user.guides.new(guide_params)

    respond_to do |format|
      if @guide.save
        format.html { redirect_to @guide, notice: 'Guía creada correctamente.' }
      else
        format.html { render :new }
      end
    end
  end
  

  def edit
   @guide = Guide.find_by_id(params[:id])
   redirect_to root_path, alert: "Operación no permitida." unless @guide
  end

  def update
    @guide = Guide.find_by_id(params[:id])
    respond_to do |format|
      if @guide.update(guide_params)
        format.html { redirect_to @guide, notice: 'Guía Actualizada.' }
      else
        format.html { render :edit }
      end
    end
  end 

 def destroy
    @guide = current_user.guides.find(params[:id])
    @guide.destroy
    respond_to do |format|
      format.html { redirect_to guides_url, notice: 'La guía fue eliminada.' }
    end
  end
  
  def index
   @guides = Guide
		.guide_list	
  end 

  def show
    redirect_to({action: :index}, notice: 'Guía no encontrada.') unless @guide
  end

  private
  def set_guide
      @guide = Guide.find_by_id(params[:id])
      @userName = User.find_by_id(@guide.user_id).name
      @comments = @guide.comments
      @commentCount = @comments.count
  end

  def guide_params
      params.require(:guide).permit(:title, :body, :photo, :category,:trophies,:user_id)
  end
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/views/guides/_form.html.erb
<%= form_with(model: guide, local: true, html: {multipart:
        true}) do |form| %>
        <div class="field">
            <%= form.label :Título %><br>
            <%= form.text_field :title, id: :guide_title %>
        </div>
        <br>

        <div class="field">
            <%= form.label :Contenido %><br>
            <%= form.text_area :body, id: :guide_body %>
        </div>
        <br>

        <div class="field">
            <%= form.label :Trofeos %><br>
            <%= form.number_field :trophies, id: :guide_trophies %>
        </div>
        <br>

        <div class="field">
            <%= form.label :Categoría %><br>
            <%= form.text_field :category, id: :guide_category %>
        </div>
        <br>

        <div class="field">
            <%= form.label :"Foto Principal" %>
            <%= form.file_field :photo, id: :guide_photo %>
        </div>
        <br>

        <div class="field">
            <%= form.hidden_field :user_id, id: :guide_author_id %>
        </div>

        <div class="actions">
            <%= form.submit "Guardar"%>
        </div>
        <% end %>

app/views/guides/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Formularios</title>
</head>

<body>
<div id="contenido">
    <div id="wrapper" style="margin: 50px 50px 50px 300px">
      <% if @guide.user_id == current_user.id %>
       <h3>Editar Guía</h3>

      <%= render 'form', guide: @guide %>

     <% else %>
      <%= controller.redirect_to root_path %>
     <% end %>
    
   </div>
</div>
</body>
</html>

app/views/guides/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Guias</title>

</head>
<body>
<div>

    <div id="contenido" class="container">

        <div id="principal">
            <h2 style="margin-left: 30%" class="ranking">Guías</h2>

            <form id="Genero" action="">

                <select name="Genero">
                    <option value="Accion">Accion</option>
                    <option value="Ciencia Ficcion">Ciencia Ficcion</option>
                    <option value="Misterio">Misterio</option>
                    <option value="Deportes">Deportes</option>
                </select>
                <br><br>
            </form>
           <% if logged_in? %>
           <div class="guia"><%= link_to " + Crear Guía", new_guide_path %></div>
            <% end %>

            <div class="menuGuias">
                <ul>
                    <li class="enlaces"><a href="">A</a></li>
                    <li class="enlaces"><a href="">B</a></li>
                    <li class="enlaces"><a href="">C</a></li>
                    <li class="enlaces"><a href="">D</a></li>
                    <li class="enlaces"><a href="">E</a></li>
                    <li class="enlaces"><a href="">F</a></li>
                    <li class="enlaces"><a href="">G</a></li>
                    <li class="enlaces"><a href="">H</a></li>
                    <li class="enlaces"><a href="">I</a></li>
                    <li class="enlaces"><a href="">J</a></li>
                    <li class="enlaces"><a href="">K</a></li>
                    <li class="enlaces"><a href="">L</a></li>
                    <li class="enlaces"><a href="">M</a></li>
                    <li class="enlaces"><a href="">N</a></li>
                    <li class="enlaces"><a href="">O</a></li>
                    <li class="enlaces"><a href="">P</a></li>
                    <li class="enlaces"><a href="">Q</a></li>
                    <li class="enlaces"><a href="">R</a></li>
                    <li class="enlaces"><a href="">S</a></li>
                    <li class="enlaces"><a href="">T</a></li>
                    <li class="enlaces"><a href="">U</a></li>
                    <li class="enlaces"><a href="">V</a></li>
                    <li class="enlaces"><a href="">W</a></li>
                    <li class="enlaces"><a href="">X</a></li>
                    <li class="enlaces"><a href="">Y</a></li>
                    <li class="enlaces"><a href="">Z</a></li>
                </ul>
            </div>

           <table id="espaciado" class="table table-striped">
            <tbody>
	    <% @guides.each do |guide| %>
                <tr>
                    <div class="pegar">
                      <div>
                    <td class="position">
                      <div>
                    <%= link_to guide_path(guide.id) do %>
                    <%= image_tag guide.photo, class:"imagui"%>
                     <% end %>
                     </div>
                    <div class="texto">
                    	
                    <a class="texto"><%= link_to guide.title, guide_path(guide.id) %></a><br>
           	    <a><%= guide.category %></a><br>
		    <a><%= guide.trophies %> trofeos</a><br>
                    <ul class="texto">
                    <li>Autor:<%= guide.name %></li>
                     </ul>
                    <td>
                        <% if logged_in? %>
                          <% if guide.user_id == current_user.id %>
                             <span class="actions">
                             <h5><%= link_to "Editar", edit_guide_path(guide.id) %></h5>
                             <h5><%= link_to "Eliminar", guide, method: :delete, data: {confirm: "seguro??"} %></h5>
                            </span>
                          <% end %>
	                <% end %>
                     </div>
                    </td>
                </tr>
	    <% end %>
            </tbody>
        </table>
                    

        <div>
            <div id="lateralGuias" class="lateralBorder">

                <h5 class="titulillo"> Mas Recientes</h5>
                <img src="image/bloodborne.jpg" alt="Blood Borne">
                <a class="auto1" href=""> Nuevo jefe para BloodBorne </a>

                <img src="image/bluedragon.jpg" alt="blue dragon">
                <a class="auto1" href=""> Blue dragon el poder del fuego.</a>

                <img src="image/starwars.jpg" alt="foto de consola">
                <a class="auto1" href="">Los secretos tras Star Wars</a>

                <img class="tamg" src="image/sega.jpg" alt="Sega">
                <a class="auto1" href="">Posible nuevo juego para Sega</a>
            </div>
        </div>
    </div>
</div>
</body>
</html>

app/views/guides/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Formularios</title>
</head>

<body>
<div id="contenido">
    <div id="wrapper" style="margin: 50px 50px 50px 300px">

<h3>Nueva Guía</h3>

<%= render 'form', guide: @guide %>

   </div>
</div>
</body>
</html>

app/views/guides/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>show of guides</title>
</head>
<body>
<div>
    <div id="contenido" class="container">
        <div id="principal">

            <h2 style="margin-left: 30%" class="ranking"><%= @guide.title %></h2>

            <p><%= @userName %> | <%= @guide.updated_at %></p>

            <div style="padding: 2% 3% 2% 0"><%= image_tag(@guide.photo) %></div>
            <p><%= @guide.body %></p>

            <h7>¡Déjanos tu comentario! </h7>
	    <%= render file:'comments/new' %>
            
            <h7>Comentarios (<%= @commentCount %>):</h7>

            <% if @commentCount > 0 %>
              <table id="espaciado" class="table table-striped">
                <tbody>
	          <% @comments.limit(@commentCount).each do |comment| %>
                    <tr>
           	      <td><%= render comment %> </td>
                    </tr>
	          <% end %>
                </tbody>
              </table>
            <% end %>
        </div>

        <div>
            <div id="lateralGuias" class="lateralBorder">
                <h5 class="titulillo"> Mas Recientes</h5>
                <%= image_tag "bloodborne.jpg" %>
                <a class="auto1" href=""> Nuevo jefe para BloodBorne </a>

                <%= image_tag "bluedragon.jpg" %>
                <a class="auto1" href=""> Blue dragon el poder del fuego.</a>

               <%= image_tag "starwars.jpg" %>
                <a class="auto1" href="">Los secretos tras Star Wars</a>

                <%= image_tag "sega.jpg" %>
                <a class="auto1" href="">Posible nuevo juego para Sega</a>
            </div>
        </div>
    </div>
</div>
</body>
</html>