config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  get '/index', to: 'welcome#index'
	
  resources :users, only: [:new, :create]
  get '/registrate', to: 'users#new'
  get '/ranking', to: 'users#show'

  resources :guides do
    resources :comments
  end

  get '/guides', to: 'guides#index'
  #post '/users/:id/guides/new', to: 'guides#new'

  resources :profiles

  resource :session, only: [:new, :create, :destroy]
  get 'login' => "sessions#new", as: "login"
  get 'logout' => "sessions#destroy", as: "logout"
  #resources :profiles do
  #  member do
  #    get :edit
  #  end
  #end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :guide
end

app/models/guide.rb
class Guide < ApplicationRecord
  mount_uploader :photo, ImageUploader

  belongs_to :user, optional: true
  has_many :comments

  scope :guide_list, -> {select('guides.id, guides.user_id, guides.photo, guides.title, guides.trophies, guides.category, guides.updated_at, users.name').joins(:user).order('guides.updated_at DESC').limit(10)}
  validates :body, :title, :trophies, :category, presence: {message: "el campo no puede quedar vacío"}
  validates :photo, presence: {message: "Debe añadir una foto"}

  def owned_by?(owner)
    return false unless owner.is_a? User
    user == owner
  end
end

app/models/profile.rb
class Profile < ApplicationRecord
  mount_uploader :photo, ImageUploader
  belongs_to :user, optional: true

  scope :minirank, -> {select('users.id, users.name, profiles.points, profiles.photo, profiles.bio').joins(:user).order('points DESC').limit(3)}
end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base

  attr_accessor :password
  before_save :encrypt_new_password
  after_create :build_profile
  
  has_one :profile
  has_many :guides, ->{order('updated_at DESC')}, dependent: :nullify
  has_many :replies, through: :guides, source: :comments

  scope :rank, -> {select('users.id, users.name, profiles.points').joins(:profile).order('points DESC').limit(10)}

  def build_profile
    Profile.create(user: self, points: 0, bio: "Hey im here using guiajuegos", categorie:"Novato", photo: '/assets/images/usuario.jpg')
  end
	
  validates :email, uniqueness: {case_sensitive: false, message: 'El correo introducido no es único'}, length: {in: 12..20, too_short: "debe tener al menos 12 caracteres"}, format: {multiline: true,with: /^.+@.+$/, message: "formato de correo no valido"}
  validates :name, uniqueness: {case_sensitive: true, message:'Este nombre ya esta siendo usado'}, length: {in: 4..10, too_short: "El nombre debe tener al menos 4 caracteres"}
  validates :password, confirmation: true, length: {within: 6..20}, presence: true
  validates :password_confirmation, presence: true

  def self.authenticate(name,password)
    user = find_by_name(name)
    return user if user && user.authenticated?(password)
  end
  
  def authenticated?(password)
    self.hashed_password == encrypt(password)
  end
  
  protected
  def encrypt_new_password
    return if password.blank?
    self.hashed_password = encrypt(password)
  end
  def password_required?
    hashed_password.blank? || password.present?
  end
  def encrypt(string)
    Digest::SHA1.hexdigest(string) 
  end

end

app/models/welcome.rb
class Welcome < ApplicationRecord
mount_uploader :photo, ImageUploader
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_guide, except: :destroy
  before_action :authenticate, only: :destroy
  
  def create
    @comment = @guide.comments.new(comment_params)
    if @comment.save
      redirect_to @guide, notice: 'gracias por su comentario'
    else
      redirect_to @guide, alert: 'no ha sido posible añadir el comentario'
    end
  end
  
  def destroy
    @guide = current_user.guides.find_by_id(params[:guide_id])
    if @guide.nil?
       redirect_to :index, notice: "operación no permitida"
     end
    @comment = @guide.comments.find_by_id(params[:id])
    @comment.destroy
    redirect_to @guide, notice: "comentario eliminado"
  end

  private
    def load_guide
      @guide = Guide.find_by_id(params[:guide_id])
    end
    
    def comment_params
      params.require(:comment).permit(:name, :body)
    end
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController
  before_action :set_guide, only: [:show]

  def new 
    @guide = Guide.new
  end

  def create
    @guide = current_user.guides.new(guide_params)

    respond_to do |format|
      if @guide.save
        format.html { redirect_to @guide, notice: 'Guía creada correctamente.' }
      else
        format.html { render :new }
      end
    end
  end
  

  def edit
   @guide = Guide.find_by_id(params[:id])
   redirect_to root_path, alert: "Operación no permitida." unless @guide
  end

  def update
    @guide = Guide.find_by_id(params[:id])
    respond_to do |format|
      if @guide.update(guide_params)
        format.html { redirect_to @guide, notice: 'Guía Actualizada.' }
      else
        format.html { render :edit }
      end
    end
  end 

 def destroy
    @guide = current_user.guides.find(params[:id])
    @guide.destroy
    respond_to do |format|
      format.html { redirect_to guides_url, notice: 'La guía fue eliminada.' }
    end
  end
  
  def index
   @guides = Guide
		.guide_list	
  end 

  def show
    redirect_to({action: :index}, notice: 'Guía no encontrada.') unless @guide
  end

  private
  def set_guide
      @guide = Guide.find_by_id(params[:id])
      @userName = User.find_by_id(@guide.user_id).name
      @comments = @guide.comments
      @commentCount = @comments.count
  end

  def guide_params
      params.require(:guide).permit(:title, :body, :photo, :category,:trophies,:user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, only: [:edit, :update]

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: "Registro completado con éxito. Verifique su correo para iniciar sesión."
    else
      render action: :new
    end
  end
  
 

  def show
    @users = User
		.rank
  end

 private
   def set_user
     @user = current_user
   end

  def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
 
  def index
   @users = Profile.all
   @ranking = @users
                    .minirank
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GuiaJuegos</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div id="header">
      <div id="guiajuegos">
        <div class="fbox">
          <div class="guia"><%= link_to "Guia", root_path %></div>
          <div class="juegos"><%= link_to "Juegos", root_path %></div>
            <div style="float: right" class="menu">
          <ul>
           <% if logged_in? %>
         
          <li><a><%= link_to current_user.name, profile_path(current_user) %></a></li>
          <li><%= link_to "Cerrar Sesión", logout_path %></li>
        <% else %>
         
          <li st><%= link_to "Registrarse", registrate_path %></li>
          <li><%= link_to "Iniciar Sesión",login_path %></li>
        <% end %>
          </div>
          </ul>
        </div>
      </div>
      <div class="menu">
        <ul>
          <li><a href="">PS4</a></li>
          <li><a href="">XBOX</a></li>
          <li><a href="">PC</a></li>
          <li><a href="">FORO</a></li>
        </ul>
        <ul>
          <li><a href="">Noticias</a></li>
          <li><a href="">Análisis</a></li>
          <li><%= link_to "Ranking", '/ranking', :method => :get %></li>
           <li><%= link_to "Guías", '/guides', :method => :get %></li>
          <li><a href="">Eventos</a></li>
          <li><a href="">Logros</a></li>
          <li><a href="">Trucos</a></li>
          
        </ul>
      </div>
      <div id="user_bar">
        
      </div>
    </div>
    <div id="main">
    <% flash.each do |name, msg| %>
       <%= content_tag :div, msg, class: name %>
    <% end %>  
    <%= yield %>
    </div>
    <div id="footer">
      <p>Realizado por Adrián Rodríguez Socorro y Kilian Luque Romero<p>
    </div>
  </body>
</html>